happy_prompts = [
    "Upbeat song with catchy melody and positive vibes",
    "Feel-good track with lively rhythm and cheerful lyrics",
    "Energetic tune with uplifting chorus and danceable beat",
    "Joyful melody with infectious groove and vibrant instrumentation",
    "Celebratory song with bright instrumentation and catchy hooks",
    "Optimistic track with sunny disposition and feel-good lyrics",
    "Party anthem with infectious rhythm and euphoric atmosphere",
    "Cheerful tune with happy-go-lucky vibe and upbeat tempo",
    "Uplifting melody with catchy hooks and inspiring lyrics",
    "Lively song with upbeat tempo and infectious energy",
    "Happy-go-lucky track with upbeat rhythm and positive vibes",
    "Feel-good anthem with uplifting chorus and memorable melody",
    "Upbeat tune with infectious beat and joyful instrumentation",
    "Positive vibes with lively rhythm and upbeat tempo",
    "Euphoric melody with catchy hooks and vibrant instrumentation",
    "Cheerful anthem with feel-good lyrics and infectious groove",
    "Vibrant track with upbeat tempo and celebratory atmosphere",
    "Sunshine-filled melody with uplifting chorus and catchy hooks",
    "Energetic tune with infectious rhythm and upbeat vibe",
    "Joyous song with lively instrumentation and uplifting lyrics",
    "Feel-good track with infectious energy and positive attitude",
    "Uplifting anthem with upbeat tempo and optimistic lyrics",
    "Happy melody with infectious rhythm and joyful atmosphere",
    "Euphoric tune with lively beat and uplifting chorus",
    "Cheerful track with bright instrumentation and catchy hooks",
    "Positive vibes with infectious rhythm and upbeat tempo",
    "Celebratory anthem with feel-good lyrics and energetic vibe",
    "Upbeat song with catchy melody and joyful atmosphere",
    "Feel-good track with vibrant instrumentation and uplifting chorus",
    "Lively tune with infectious rhythm and positive energy"
]

sad_prompts = [
    "Melancholic song with slow tempo and heartfelt lyrics",
    "Emotional track with somber melody and introspective vibe",
    "Heartbreaking tune with poignant lyrics and melancholy atmosphere",
    "Sad ballad with soulful vocals and poignant instrumentation",
    "Tearjerker song with emotive chorus and melancholic melody",
    "Sorrowful melody with haunting vocals and introspective lyrics",
    "Emotionally-charged track with melancholy atmosphere and introspective vibe",
    "Grief-stricken tune with haunting vocals and soulful instrumentation",
    "Heartfelt ballad with poignant lyrics and melancholic undertones",
    "Reflective song with somber melody and introspective atmosphere",
    "Poignant melody with emotive vocals and melancholic instrumentation",
    "Sad anthem with soul-stirring chorus and heartfelt lyrics",
    "Melancholy tune with haunting vocals and introspective vibe",
    "Emotional track with somber atmosphere and introspective lyrics",
    "Heart-wrenching ballad with poignant vocals and melancholic melody",
    "Sorrowful song with haunting instrumentation and introspective vibe",
    "Reflective melody with melancholic undertones and emotive vocals",
    "Tearful tune with soul-stirring chorus and poignant lyrics",
    "Sad ballad with haunting vocals and melancholic instrumentation",
    "Emotionally-charged track with somber atmosphere and introspective vibe",
    "Grief-stricken melody with emotive vocals and melancholy undertones",
    "Heartfelt song with soulful lyrics and poignant melody",
    "Reflective tune with melancholic atmosphere and introspective lyrics",
    "Poignant anthem with haunting vocals and emotive instrumentation",
    "Melancholy track with soul-stirring chorus and heartfelt lyrics",
    "Emotional ballad with somber melody and introspective vibe",
    "Sad song with haunting vocals and melancholic atmosphere",
    "Tearjerker melody with emotive lyrics and poignant instrumentation",
    "Heartbreaking tune with soulful vocals and melancholy undertones",
    "Sorrowful track with emotive chorus and haunting atmosphere"
]

anger_prompts = [
    "Fiery song with aggressive rhythm and intense vocals",
    "Angry track with explosive energy and powerful instrumentation",
    "Aggressive tune with thunderous drums and fierce guitars",
    "Rage-filled anthem with intense vocals and aggressive atmosphere",
    "Furious melody with pounding rhythm and blistering guitars",
    "Hostile song with aggressive lyrics and relentless tempo",
    "Intense track with explosive energy and ferocious vocals",
    "Provocative tune with angry lyrics and heavy instrumentation",
    "Outrageous anthem with fiery vocals and aggressive rhythm",
    "Angry melody with pounding drums and aggressive guitars",
    "Furious song with blistering tempo and intense atmosphere",
    "Aggressive track with thunderous drums and relentless energy",
    "Rage-filled tune with fierce vocals and aggressive instrumentation",
    "Hostile anthem with fiery lyrics and pounding rhythm",
    "Provocative melody with angry vocals and intense guitars",
    "Outrageous song with aggressive atmosphere and intense tempo",
    "Fiery track with explosive energy and fierce vocals",
    "Angry tune with relentless rhythm and pounding drums",
    "Aggressive melody with blistering guitars and ferocious vocals",
    "Rage-filled anthem with intense atmosphere and aggressive lyrics",
    "Furious song with aggressive instrumentation and fiery vocals",
    "Intense track with pounding drums and relentless energy",
    "Provocative tune with angry lyrics and intense atmosphere",
    "Outrageous melody with aggressive guitars and pounding rhythm",
    "Angry anthem with ferocious vocals and blistering tempo",
    "Fiery song with aggressive rhythm and relentless energy",
    "Aggressive track with intense vocals and pounding drums",
    "Rage-filled tune with fiery atmosphere and aggressive guitars",
    "Furious melody with relentless tempo and intense vocals",
    "Hostile song with pounding rhythm and angry lyrics"
]

neutral_prompts = [
    "Relaxing instrumental with soothing melody and tranquil atmosphere",
    "Chill-out track with mellow vibe and laid-back rhythm",
    "Ambient tune with atmospheric sounds and serene instrumentation",
    "Peaceful melody with gentle vocals and calming atmosphere",
    "Tranquil song with soothing vocals and ethereal instrumentation",
    "Mellow track with relaxed tempo and dreamy vibe",
    "Soothing tune with calming melody and tranquil atmosphere",
    "Laid-back anthem with chilled-out rhythm and serene vocals",
    "Easygoing melody with mellow vibe and peaceful atmosphere",
    "Tranquil song with gentle vocals and ambient instrumentation",
    "Relaxing track with soothing melody and tranquil atmosphere",
    "Chill-out tune with mellow rhythm and laid-back atmosphere",
    "Ambient melody with ethereal vocals and serene instrumentation",
    "Peaceful song with calming chorus and dreamy atmosphere",
    "Tranquil track with soothing vocals and gentle instrumentation",
    "Mellow anthem with relaxed tempo and chill vibe",
    "Soothing melody with calming vocals and ambient atmosphere",
    "Laid-back song with chilled-out rhythm and dreamy vibe",
    "Easygoing tune with mellow melody and peaceful atmosphere",
    "Tranquil track with gentle vocals and atmospheric instrumentation",
    "Relaxing anthem with soothing chorus and serene atmosphere",
    "Chill-out melody with laid-back rhythm and ethereal vocals",
    "Ambient tune with atmospheric sounds and serene instrumentation",
    "Peaceful melody with gentle vocals and calming atmosphere",
    "Tranquil song with soothing vocals and ethereal instrumentation",
    "Mellow track with relaxed tempo and dreamy vibe",
    "Soothing tune with calming melody and tranquil atmosphere",
    "Laid-back anthem with chilled-out rhythm and serene vocals",
    "Easygoing melody with mellow vibe and peaceful atmosphere",
    "Tranquil song with gentle vocals and ambient instrumentation",
    "Relaxing track with soothing melody and tranquil atmosphere",
    "Chill-out tune with mellow rhythm and laid-back atmosphere",
    "Ambient melody with ethereal vocals and serene instrumentation",
    "Peaceful song with calming chorus and dreamy atmosphere",
    "Tranquil track with soothing vocals and gentle instrumentation",
    "Mellow anthem with relaxed tempo and chill vibe",
    "Soothing melody with calming vocals and ambient atmosphere",
    "Laid-back song with chilled-out rhythm and dreamy vibe",
    "Easygoing tune with mellow melody and peaceful atmosphere",
    "Tranquil track with gentle vocals and atmospheric instrumentation",
    "Relaxing anthem with soothing chorus and serene atmosphere",
    "Chill-out melody with laid-back rhythm and ethereal vocals",
    "Ambient tune with tranquil atmosphere and soothing instrumentation",
    "Peaceful track with calming melody and gentle vocals",
    "Tranquil song with mellow rhythm and dreamy atmosphere",
    "Soothing melody with relaxing instrumentation and peaceful vibe",
    "Laid-back anthem with serene vocals and chilled-out rhythm",
    "Easygoing tune with mellow vibe and tranquil atmosphere",
    "Tranquil track with soothing vocals and atmospheric sounds"
]

surprise_prompts = [
    "Surprising track with unexpected twists and dynamic changes",
    "Unpredictable melody with sudden shifts and surprising elements",
    "Unexpected tune with surprising rhythm and unpredictable instrumentation",
    "Shocking song with surprising chorus and unexpected lyrics",
    "Startling track with sudden tempo changes and surprising vocals",
    "Unforeseen melody with unexpected twists and surprising atmosphere",
    "Surprising anthem with sudden shifts and dynamic energy",
    "Spontaneous tune with surprising rhythm changes and unexpected hooks",
    "Jolting song with unexpected chorus and startling instrumentation",
    "Unexpected melody with surprising vocals and dynamic changes",
    "Surprising track with sudden tempo shifts and unexpected transitions",
    "Unpredictable tune with surprising rhythm patterns and dynamic instrumentation",
    "Unexpected anthem with sudden changes and surprising energy",
    "Startling melody with unexpected twists and surprising atmosphere",
    "Surprising song with sudden shifts and unexpected lyrics",
    "Shocking track with surprising chorus and dynamic changes",
    "Unforeseen tune with unexpected rhythm patterns and surprising vocals",
    "Spontaneous melody with sudden shifts and surprising instrumentation",
    "Jolting anthem with unexpected hooks and dynamic energy",
    "Surprising track with sudden tempo changes and surprising transitions",
    "Unpredictable tune with unexpected twists and dynamic instrumentation",
    "Unexpected melody with surprising rhythm patterns and surprising vocals",
    "Surprising song with sudden changes and unexpected atmosphere",
    "Startling track with unexpected hooks and surprising energy",
    "Unforeseen tune with sudden shifts and dynamic changes",
    "Surprising anthem with surprising chorus and unexpected transitions",
    "Shocking melody with sudden twists and surprising instrumentation",
    "Unexpected song with surprising rhythm and dynamic atmosphere",
    "Spontaneous track with sudden changes and unexpected elements"
]

fear_prompts = [
    "Chilling track with eerie atmosphere and haunting vocals",
    "Terrifying melody with ominous undertones and unsettling instrumentation",
    "Fear-inducing tune with suspenseful rhythm and ominous atmosphere",
    "Spine-tingling song with chilling vocals and unsettling melody",
    "Creepy track with haunting chorus and eerie instrumentation",
    "Horror-themed melody with suspenseful buildup and terrifying climax",
    "Petrifying anthem with ominous vocals and chilling atmosphere",
    "Dreadful tune with unsettling rhythm and eerie vocals",
    "Tense song with chilling chorus and suspenseful instrumentation",
    "Gothic track with dark atmosphere and menacing melody",
    "Nightmarish melody with sinister undertones and haunting vocals",
    "Anxiety-inducing tune with eerie rhythm and unsettling atmosphere",
    "Scary anthem with haunting vocals and suspenseful buildup",
    "Spooky melody with chilling hooks and ominous instrumentation",
    "Terror-filled song with eerie chorus and suspenseful atmosphere",
    "Frightening track with ominous undertones and chilling vocals",
    "Creepy tune with suspenseful buildup and terrifying climax",
    "Horror-themed anthem with eerie atmosphere and haunting melody",
    "Petrifying melody with chilling vocals and ominous instrumentation",
    "Dreadful song with unsettling chorus and suspenseful rhythm",
    "Tense track with ominous undertones and eerie atmosphere",
    "Gothic tune with haunting vocals and menacing melody",
    "Nightmarish melody with suspenseful buildup and chilling climax",
    "Anxiety-inducing anthem with eerie chorus and unsettling rhythm",
    "Scary melody with chilling hooks and suspenseful instrumentation",
    "Spooky song with ominous atmosphere and haunting vocals",
    "Terror-filled track with eerie rhythm and suspenseful buildup",
    "Frightening tune with chilling vocals and unsettling melody",
    "Creepy anthem with suspenseful atmosphere and haunting chorus",
    "Horror-themed melody with ominous undertones and terrifying climax"
]

prompts = {
    "happy": happy_prompts,
    "sad": sad_prompts,
    "anger": anger_prompts,
    "neutral": neutral_prompts,
    "surprise": surprise_prompts,
    "fear": fear_prompts
}

file_path = "prompts.txt"

with open(file_path, "w") as f:
    for category, category_prompts in prompts.items():
        for i, prompt in enumerate(category_prompts, start=1):
            f.write(f"{category}: {prompt}\n")
        f.write("\n")

print("Prompts saved successfully.")